[lint]
ignore = [
    "C901",
    "ASYNC240",
    "ASYNC109",
    "N818",
    "UP042",
    "W293",
    "BLE001",
    "G201",
    "RUF059",
    "SIM117",
    "B008",
    "PIE810",
    "S110",
    "C414",
    "RUF013",
]
